In [7]:
### Exercise 6 
# part 1

# install the packages
import pandas as pd
import matplotlib.pyplot as plt
import os

# download data 
df = pd.read_csv("data/firm_data_ex06.csv")
# need to add the function panda helps to read the csv file

In [8]:
# use OS
#  otherway to download the data using the absolute path 
# it finds the path directly in your computer using the name of the file

PATH_OF_CURRENT_FOLDER = os.getcwd()
P_Research = PATH_OF_CURRENT_FOLDER
data_path = os.path.join(P_Research, "data", "firm_data_ex06.csv")

# read the path
df = pd.read_csv(data_path)
df.head()

,ticker,date,gvkey,comp_name,fiscal_year,fiscal_quarter,assets,net_income,ebitda,revenue,rd_expense,cap_ex_ytd,sector_code
0,AAPL,2005-03-31,1690,APPLE INC,2005,2,10111.0,286.0,438.0,3243.0,120.0,101.0,45
1,AAPL,2005-06-30,1690,APPLE INC,2005,3,10488.0,319.0,472.0,3520.0,145.0,164.0,45
2,AAPL,2005-09-30,1690,APPLE INC,2005,4,11551.0,428.0,468.0,3678.0,147.0,260.0,45
3,AAPL,2005-12-31,1690,APPLE INC,2006,1,14181.0,565.0,802.0,5749.0,182.0,82.0,45
4,AAPL,2006-03-31,1690,APPLE INC,2006,2,13911.0,410.0,579.0,4359.0,176.0,275.0,45

In [11]:
# compact version
base_dir = os.getcwd()
file_path = os.path.join(base_dir, "data", "firm_data_ex06.csv") 
# load the data
df = pd.read_csv(file_path)
df.head()

,ticker,date,gvkey,comp_name,fiscal_year,fiscal_quarter,assets,net_income,ebitda,revenue,rd_expense,cap_ex_ytd,sector_code
0,AAPL,2005-03-31,1690,APPLE INC,2005,2,10111.0,286.0,438.0,3243.0,120.0,101.0,45
1,AAPL,2005-06-30,1690,APPLE INC,2005,3,10488.0,319.0,472.0,3520.0,145.0,164.0,45
2,AAPL,2005-09-30,1690,APPLE INC,2005,4,11551.0,428.0,468.0,3678.0,147.0,260.0,45
3,AAPL,2005-12-31,1690,APPLE INC,2006,1,14181.0,565.0,802.0,5749.0,182.0,82.0,45
4,AAPL,2006-03-31,1690,APPLE INC,2006,2,13911.0,410.0,579.0,4359.0,176.0,275.0,45

In [15]:
## Exo 0.2 
unique_nb = df["ticker"].nunique()
print(f"The number of unique ticker is {unique_nb}")

unique_name = df["ticker"].unique().tolist()
print(f"the name of the unique ticker are: {unique_name}")

The number of unique ticker is 10
the name of the unique ticker are: ['AAPL', 'F', 'GM', 'GOOGL', 'INTC', 'MSFT', 'NVDA', 'TM', 'TSLA', 'VWAGY']

In [ ]:
## Exo 0.3 (my version)
number_obs = df.groupby("ticker").count()
print(number_obs["comp_name"])

ticker
AAPL     84
F        84
GM       84
GOOGL    84
INTC     84
MSFT     84
NVDA     85
TM       84
TSLA     72
VWAGY    82
Name: comp_name, dtype: int64

In [19]:
## Exo 0.3 (correction)
# .value_counts() tells us how many rows exist for each unique entry
print("\nObservations per company:")
print(df['comp_name'].value_counts())

Observations per company:
comp_name
NVIDIA CORP          85
APPLE INC            84
FORD MOTOR CO        84
GENERAL MOTORS CO    84
ALPHABET INC         84
INTEL CORP           84
MICROSOFT CORP       84
TOYOTA MOTOR CORP    84
VOLKSWAGEN AG        82
TESLA INC            72
Name: count, dtype: int64

In [23]:
## Exo 0.4
max_date = df["date"].max()
min_date = df["date"].min()
print(f"earliest date si {min_date} and latest entry is {max_date}")

earliest date si 2005-01-31 and latest entry is 2026-01-31

In [ ]:
## Exo 0.4 (correction)
# Note: Because the dates are currently loaded as strings, pandas finds the 
# min/max by sorting them alphabetically. This only works correctly if 
# the strings are perfectly formatted as YYYY-MM-DD!

print(f"\nData starts on: {df['date'].min()}")
print(f"Data ends on:   {df['date'].max()}")

Exercise 1: Identifying and Handling Missing Data
In the lecture, we discussed how the 2025 federal shutdown caused a gap in official unemployment statistics. Corporate financial data is often much messier and contains structural missing values (NaNs) because different industries/firms follow different reporting standards. This exercise focuses on identifying these gaps and applying appropriate strategies to handle them.

Part A: Identifying Gaps
Before fixing data, you must understand where it is broken. We start by quantifying the missing values in our dataset.

Your Tasks

Overview: Use the .info() method to get a high-level summary of the dataset. Which columns appear to have the most missing values?

Quantification: Calculate the exact number of NaN entries for every variable.

Identify Affected Firms: Pinpoint exactly which companies have missing data for a specific variable (e.g., assets). Create a subset of the data containing only the rows where that variable is NaN, then extract a list of the unique company names.