In [7]:
### Exercise 6 
# part 1

# install the packages
import pandas as pd
import matplotlib.pyplot as plt
import os

# download data 
df = pd.read_csv("data/firm_data_ex06.csv")
# need to add the function panda helps to read the csv file

In [8]:
# use OS
#  otherway to download the data using the absolute path 
# it finds the path directly in your computer using the name of the file

PATH_OF_CURRENT_FOLDER = os.getcwd()
P_Research = PATH_OF_CURRENT_FOLDER
data_path = os.path.join(P_Research, "data", "firm_data_ex06.csv")

# read the path
df = pd.read_csv(data_path)
df.head()

,ticker,date,gvkey,comp_name,fiscal_year,fiscal_quarter,assets,net_income,ebitda,revenue,rd_expense,cap_ex_ytd,sector_code
0,AAPL,2005-03-31,1690,APPLE INC,2005,2,10111.0,286.0,438.0,3243.0,120.0,101.0,45
1,AAPL,2005-06-30,1690,APPLE INC,2005,3,10488.0,319.0,472.0,3520.0,145.0,164.0,45
2,AAPL,2005-09-30,1690,APPLE INC,2005,4,11551.0,428.0,468.0,3678.0,147.0,260.0,45
3,AAPL,2005-12-31,1690,APPLE INC,2006,1,14181.0,565.0,802.0,5749.0,182.0,82.0,45
4,AAPL,2006-03-31,1690,APPLE INC,2006,2,13911.0,410.0,579.0,4359.0,176.0,275.0,45

In [11]:
# compact version
base_dir = os.getcwd()
file_path = os.path.join(base_dir, "data", "firm_data_ex06.csv") 
# load the data
df = pd.read_csv(file_path)
df.head()

,ticker,date,gvkey,comp_name,fiscal_year,fiscal_quarter,assets,net_income,ebitda,revenue,rd_expense,cap_ex_ytd,sector_code
0,AAPL,2005-03-31,1690,APPLE INC,2005,2,10111.0,286.0,438.0,3243.0,120.0,101.0,45
1,AAPL,2005-06-30,1690,APPLE INC,2005,3,10488.0,319.0,472.0,3520.0,145.0,164.0,45
2,AAPL,2005-09-30,1690,APPLE INC,2005,4,11551.0,428.0,468.0,3678.0,147.0,260.0,45
3,AAPL,2005-12-31,1690,APPLE INC,2006,1,14181.0,565.0,802.0,5749.0,182.0,82.0,45
4,AAPL,2006-03-31,1690,APPLE INC,2006,2,13911.0,410.0,579.0,4359.0,176.0,275.0,45